#!/bin/bash

function getCurSinkName() {
  if ! pactl info &> /dev/null; then return 1; fi
    curSinkName=$(pactl info | awk -F : '/Default Sink:/{print $2}')
}

function getCurSink() {
    getCurSinkName
    curSink=$(pactl list sinks short | grep $curSinkName | awk '{print $1}')
}

function getCurVol() {
    VOL_LEVEL=$(pactl list sinks | grep -A 15 'Sink #'"$1"'' | grep 'Volume:' | grep -E -v 'Base Volume:' | awk -F : '{print $3; exit}' | grep -o -P '.{0,3}%' | sed 's/.$//' | tr -d ' ')
}

function getIsMuted() {
    isMuted=$(pactl list sinks | grep -A 15 'Sink #'"$1"'' | awk '/Mute/ {print $2; exit}')
}

function getSinks() {
    sinks=$(pactl -f json list sinks)
}

function output() {
    getSinks
    getCurSink
    getCurVol "$curSink"
    getIsMuted "$curSink"

    if [ "$isMuted" = "yes" ]; then
        eww update volume-muted=true &
    else
        eww update volume-muted=false &
    fi

    eww update audio-sinks="${sinks}" &
    eww update audio-sink-current="${curSink}" &

    echo $VOL_LEVEL
}

# Print on first run
output

# Print when the volume changes
pactl subscribe 2>/dev/null | {
    while true; do
        {
            read -r event || break
            if ! echo "$event" | grep -e "on card" -e "on sink" -e "on server"; then
                continue
            fi
        } &>/dev/null
        output
    done
}
