#!/bin/bash

function getCurrSinkName() {
  if ! pactl info &> /dev/null; then return 1; fi
    curSinkName=$(pactl info | awk -F : '/Default Sink:/{print $2}')
}

function getCurSink() {
    getCurrSinkName
    curSink=$(pactl list sinks short | grep $curSinkName | awk '{print $1}')
}

function getCurVol() {
    VOL_LEVEL=$(pactl list sinks | grep -A 15 'Sink #'"$1"'' | grep 'Volume:' | grep -E -v 'Base Volume:' | awk -F : '{print $3; exit}' | grep -o -P '.{0,3}%' | sed 's/.$//' | tr -d ' ')
}

function getIsMuted() {
    isMuted=$(pactl list sinks | grep -A 15 'Sink #'"$1"'' | awk '/Mute/ {print $2; exit}')
}

function output() {
    getCurSink
    getCurVol "$curSink"
    getIsMuted "$curSink"

    if [ "$isMuted" = "yes" ]; then
        echo "muted"
    else
        echo $VOL_LEVEL
    fi
}

# Print on first run
output

# Print when the volume changes
pactl subscribe 2>/dev/null | {
    while true; do
        {
            read -r event || break
            if ! echo "$event" | grep -e "on card" -e "on sink" -e "on server"; then
                continue
            fi
        } &>/dev/null
        output
    done
}
