#!/usr/bin/env bash

EWW_CMD=eww

./scripts/hide-widgets &
./scripts/hide-system-menu &

$EWW_CMD open-many --toggle control-center-window-closer-0 control-center-window-closer-1 control-center-window-closer-2

revealed=$($EWW_CMD get reveal_control_center)

if [[ $revealed == "true" ]]; then
    $EWW_CMD update reveal_control_center="false" &
else
    $EWW_CMD update reveal_control_center="true" &
fi
