#!/usr/bin/env bash

EWW_CMD=eww

group=$($EWW get reveal-notification-group)

if [[ $group == $1 ]]; then
    $EWW update reveal-notification-group="null"
else
    $EWW update reveal-notification-group="$1"
fi
