#!/usr/bin/env bash

EWW=eww

IFS=","
read -a revealed <<< "$($EWW get reveal_widgets)"
revealed[0]=${revealed[0]#[}
revealed[-1]=${revealed[-1]%]}
monitors=(false false false)

if [[ "${revealed[$1]}" == "true" ]]; then
    monitors[$1]=false
    $EWW update reveal_widgets="[${monitors[0]},${monitors[1]},${monitors[2]}]"
else
    monitors[$1]=true
    $EWW update reveal_widgets="[${monitors[0]},${monitors[1]},${monitors[2]}]"
fi
