#!/usr/bin/env bash

EWW_CMD=eww

./scripts/hide-control-center &
./scripts/hide-widgets &

$EWW_CMD open-many --toggle system-menu-window-closer-0 system-menu-window-closer-1 system-menu-window-closer-2

IFS=","
read -a revealed <<< "$($EWW_CMD get reveal_system_menu)"
revealed[0]=${revealed[0]#[}
revealed[-1]=${revealed[-1]%]}
monitors=(false false false)

if [[ "${revealed[$1]}" == "true" ]]; then
    monitors[$1]=false
    $EWW_CMD update reveal_system_menu="[${monitors[0]},${monitors[1]},${monitors[2]}]" &
else
    monitors[$1]=true
    $EWW_CMD update reveal_system_menu="[${monitors[0]},${monitors[1]},${monitors[2]}]" &
fi
