#!/usr/bin/env bash

EWW=eww

result=$($EWW get expand-notification-groups)

if [[ $result == "true" ]]; then
    $EWW update expand-notification-groups="false" &
else
    $EWW update expand-notification-groups="true" &
fi
